// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE6hH939O7FgAkNO6PTHO-VCElQrQaSuc',
    appId: '1:811237248062:web:2aca07b84866b58d1f156f',
    messagingSenderId: '811237248062',
    projectId: 'lostfound2025',
    authDomain: 'lostfound2025.firebaseapp.com',
    storageBucket: 'lostfound2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6HOK_iD6BoP92FRLGQWXb6uD8BjJQdrs',
    appId: '1:811237248062:android:841da4db78a967ec1f156f',
    messagingSenderId: '811237248062',
    projectId: 'lostfound2025',
    storageBucket: 'lostfound2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJjXa2YAroVUt0mmhc-Uabjl6KofaOYe4',
    appId: '1:811237248062:ios:a080f0f9821647b01f156f',
    messagingSenderId: '811237248062',
    projectId: 'lostfound2025',
    storageBucket: 'lostfound2025.firebasestorage.app',
    iosBundleId: 'com.example.lostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJjXa2YAroVUt0mmhc-Uabjl6KofaOYe4',
    appId: '1:811237248062:ios:a080f0f9821647b01f156f',
    messagingSenderId: '811237248062',
    projectId: 'lostfound2025',
    storageBucket: 'lostfound2025.firebasestorage.app',
    iosBundleId: 'com.example.lostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE6hH939O7FgAkNO6PTHO-VCElQrQaSuc',
    appId: '1:811237248062:web:ea663300981096901f156f',
    messagingSenderId: '811237248062',
    projectId: 'lostfound2025',
    authDomain: 'lostfound2025.firebaseapp.com',
    storageBucket: 'lostfound2025.firebasestorage.app',
  );
}
